- fix in checking is netforking is up.
Changed files:
    ldap.init -> 1.5

diff --git a/ldap.init b/ldap.init
--- a/ldap.init
+++ b/ldap.init
@@ -20,7 +20,10 @@
 [ -f /etc/sysconfig/ldap ] && . /etc/sysconfig/ldap
 
 # Check that networking is up.
-[ "${NETWORKING}" = "no" ] && echo "Error: Networking is down" && exit 0
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Ldap service can't be runed."
+	exit 1
+fi
 
 
 # See how we were called.
